package bean;
// Generated 15/10/2025 12:59:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LfsCliente generated by hbm2java
 */
@Entity
@Table(name="lfs_cliente"
    ,catalog="db_laura_silva"
)
public class LfsCliente  implements java.io.Serializable {


     private int idlfsCliente;
     private String lfsNomeCompleto;
     private int lfsGenero;
     private String lfsCpf;
     private Date lfsDataNascimento;
     private String lfsSenha;
     private String lfsRg;
     private String lfsCep;
     private String lfsEmail;
     private String lfsTelefone;
     private int lfsFormaPagamento;
     private Date lfsDataUltimoLogin;
     private String lfsPreferencias;
     private String lfsObservacoes;
     private Date lfsDataCadastro;
     private String lfsCnpj;

    public LfsCliente() {
    }

	
    public LfsCliente(int idlfsCliente, String lfsNomeCompleto, int lfsGenero, String lfsCpf, String lfsSenha, String lfsRg, String lfsCep, String lfsEmail, String lfsTelefone, int lfsFormaPagamento, String lfsPreferencias, String lfsObservacoes) {
        this.idlfsCliente = idlfsCliente;
        this.lfsNomeCompleto = lfsNomeCompleto;
        this.lfsGenero = lfsGenero;
        this.lfsCpf = lfsCpf;
        this.lfsSenha = lfsSenha;
        this.lfsRg = lfsRg;
        this.lfsCep = lfsCep;
        this.lfsEmail = lfsEmail;
        this.lfsTelefone = lfsTelefone;
        this.lfsFormaPagamento = lfsFormaPagamento;
        this.lfsPreferencias = lfsPreferencias;
        this.lfsObservacoes = lfsObservacoes;
    }
    public LfsCliente(int idlfsCliente, String lfsNomeCompleto, int lfsGenero, String lfsCpf, Date lfsDataNascimento, String lfsSenha, String lfsRg, String lfsCep, String lfsEmail, String lfsTelefone, int lfsFormaPagamento, Date lfsDataUltimoLogin, String lfsPreferencias, String lfsObservacoes, Date lfsDataCadastro, String lfsCnpj, Set lfsVendas) {
       this.idlfsCliente = idlfsCliente;
       this.lfsNomeCompleto = lfsNomeCompleto;
       this.lfsGenero = lfsGenero;
       this.lfsCpf = lfsCpf;
       this.lfsDataNascimento = lfsDataNascimento;
       this.lfsSenha = lfsSenha;
       this.lfsRg = lfsRg;
       this.lfsCep = lfsCep;
       this.lfsEmail = lfsEmail;
       this.lfsTelefone = lfsTelefone;
       this.lfsFormaPagamento = lfsFormaPagamento;
       this.lfsDataUltimoLogin = lfsDataUltimoLogin;
       this.lfsPreferencias = lfsPreferencias;
       this.lfsObservacoes = lfsObservacoes;
       this.lfsDataCadastro = lfsDataCadastro;
       this.lfsCnpj = lfsCnpj;
     
    }
   
     @Id 

    
    @Column(name="idlfs_Cliente", unique=true, nullable=false)
    public int getIdlfsCliente() {
        return this.idlfsCliente;
    }
    
    public void setIdlfsCliente(int idlfsCliente) {
        this.idlfsCliente = idlfsCliente;
    }

    
    @Column(name="lfs_Nome_completo", nullable=false, length=45)
    public String getLfsNomeCompleto() {
        return this.lfsNomeCompleto;
    }
    
    public void setLfsNomeCompleto(String lfsNomeCompleto) {
        this.lfsNomeCompleto = lfsNomeCompleto;
    }

    
    @Column(name="lfs_genero", nullable=false)
    public int getLfsGenero() {
        return this.lfsGenero;
    }
    
    public void setLfsGenero(int lfsGenero) {
        this.lfsGenero = lfsGenero;
    }

    
    @Column(name="lfs_cpf", nullable=false, length=14)
    public String getLfsCpf() {
        return this.lfsCpf;
    }
    
    public void setLfsCpf(String lfsCpf) {
        this.lfsCpf = lfsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lfs_dataNascimento", length=10)
    public Date getLfsDataNascimento() {
        return this.lfsDataNascimento;
    }
    
    public void setLfsDataNascimento(Date lfsDataNascimento) {
        this.lfsDataNascimento = lfsDataNascimento;
    }

    
    @Column(name="lfs_senha", nullable=false, length=10)
    public String getLfsSenha() {
        return this.lfsSenha;
    }
    
    public void setLfsSenha(String lfsSenha) {
        this.lfsSenha = lfsSenha;
    }

    
    @Column(name="lfs_RG", nullable=false, length=9)
    public String getLfsRg() {
        return this.lfsRg;
    }
    
    public void setLfsRg(String lfsRg) {
        this.lfsRg = lfsRg;
    }

    
    @Column(name="lfs_Cep", nullable=false, length=8)
    public String getLfsCep() {
        return this.lfsCep;
    }
    
    public void setLfsCep(String lfsCep) {
        this.lfsCep = lfsCep;
    }

    
    @Column(name="lfs_email", nullable=false, length=20)
    public String getLfsEmail() {
        return this.lfsEmail;
    }
    
    public void setLfsEmail(String lfsEmail) {
        this.lfsEmail = lfsEmail;
    }

    
    @Column(name="lfs_telefone", nullable=false, length=15)
    public String getLfsTelefone() {
        return this.lfsTelefone;
    }
    
    public void setLfsTelefone(String lfsTelefone) {
        this.lfsTelefone = lfsTelefone;
    }

    
    @Column(name="lfs_forma_pagamento", nullable=false)
    public int getLfsFormaPagamento() {
        return this.lfsFormaPagamento;
    }
    
    public void setLfsFormaPagamento(int lfsFormaPagamento) {
        this.lfsFormaPagamento = lfsFormaPagamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lfs_dataUltimoLogin", length=10)
    public Date getLfsDataUltimoLogin() {
        return this.lfsDataUltimoLogin;
    }
    
    public void setLfsDataUltimoLogin(Date lfsDataUltimoLogin) {
        this.lfsDataUltimoLogin = lfsDataUltimoLogin;
    }

    
    @Column(name="lfs_preferencias", nullable=false, length=200)
    public String getLfsPreferencias() {
        return this.lfsPreferencias;
    }
    
    public void setLfsPreferencias(String lfsPreferencias) {
        this.lfsPreferencias = lfsPreferencias;
    }

    
    @Column(name="lfs_observacoes", nullable=false, length=100)
    public String getLfsObservacoes() {
        return this.lfsObservacoes;
    }
    
    public void setLfsObservacoes(String lfsObservacoes) {
        this.lfsObservacoes = lfsObservacoes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lfs_dataCadastro", length=10)
    public Date getLfsDataCadastro() {
        return this.lfsDataCadastro;
    }
    
    public void setLfsDataCadastro(Date lfsDataCadastro) {
        this.lfsDataCadastro = lfsDataCadastro;
    }

    
    @Column(name="lfs_cnpj", length=20)
    public String getLfsCnpj() {
        return this.lfsCnpj;
    }
    
    public void setLfsCnpj(String lfsCnpj) {
        this.lfsCnpj = lfsCnpj;
    }

    @Override
    public String toString() {
        return this.getLfsNomeCompleto();
    }
    




}


