package bean;
// Generated 15/10/2025 12:59:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LfsJogos generated by hbm2java
 */
@Entity
@Table(name="lfs_jogos"
    ,catalog="db_laura_silva"
)
public class LfsJogos  implements java.io.Serializable {


     private int lfsIdJogo;
     private String lfsNomeJogo;
     private String lfsClassificacaoIndicativa;
     private String lfsGenero;
     private double lfsPreco;
     private String lfsDescricao;
     private Date lfsDataLancamento;
     private String lfsEstoque;
     private String lfsIdioma;
     private Date lfsDataAdicionado;
     private String lfsDesenvolvedora;
     private String lfsAvaliacaoMedia;
     private String lfsModoDeJogo;
     private String lfsPlataforma;
     private String lfsStatusDisponibilidade;
  

    public LfsJogos() {
    }

	
    public LfsJogos(int lfsIdJogo, String lfsNomeJogo, String lfsClassificacaoIndicativa, String lfsGenero, double lfsPreco, String lfsDescricao, String lfsEstoque, String lfsIdioma, String lfsDesenvolvedora, String lfsAvaliacaoMedia, String lfsModoDeJogo, String lfsPlataforma, String lfsStatusDisponibilidade) {
        this.lfsIdJogo = lfsIdJogo;
        this.lfsNomeJogo = lfsNomeJogo;
        this.lfsClassificacaoIndicativa = lfsClassificacaoIndicativa;
        this.lfsGenero = lfsGenero;
        this.lfsPreco = lfsPreco;
        this.lfsDescricao = lfsDescricao;
        this.lfsEstoque = lfsEstoque;
        this.lfsIdioma = lfsIdioma;
        this.lfsDesenvolvedora = lfsDesenvolvedora;
        this.lfsAvaliacaoMedia = lfsAvaliacaoMedia;
        this.lfsModoDeJogo = lfsModoDeJogo;
        this.lfsPlataforma = lfsPlataforma;
        this.lfsStatusDisponibilidade = lfsStatusDisponibilidade;
    }
    public LfsJogos(int lfsIdJogo, String lfsNomeJogo, String lfsClassificacaoIndicativa, String lfsGenero, double lfsPreco, String lfsDescricao, Date lfsDataLancamento, String lfsEstoque, String lfsIdioma, Date lfsDataAdicionado, String lfsDesenvolvedora, String lfsAvaliacaoMedia, String lfsModoDeJogo, String lfsPlataforma, String lfsStatusDisponibilidade, Set lfsVendasJogoses) {
       this.lfsIdJogo = lfsIdJogo;
       this.lfsNomeJogo = lfsNomeJogo;
       this.lfsClassificacaoIndicativa = lfsClassificacaoIndicativa;
       this.lfsGenero = lfsGenero;
       this.lfsPreco = lfsPreco;
       this.lfsDescricao = lfsDescricao;
       this.lfsDataLancamento = lfsDataLancamento;
       this.lfsEstoque = lfsEstoque;
       this.lfsIdioma = lfsIdioma;
       this.lfsDataAdicionado = lfsDataAdicionado;
       this.lfsDesenvolvedora = lfsDesenvolvedora;
       this.lfsAvaliacaoMedia = lfsAvaliacaoMedia;
       this.lfsModoDeJogo = lfsModoDeJogo;
       this.lfsPlataforma = lfsPlataforma;
       this.lfsStatusDisponibilidade = lfsStatusDisponibilidade;
      
    }
   
     @Id 

    
    @Column(name="lfs_id_jogo", unique=true, nullable=false)
    public int getLfsIdJogo() {
        return this.lfsIdJogo;
    }
    
    public void setLfsIdJogo(int lfsIdJogo) {
        this.lfsIdJogo = lfsIdJogo;
    }

    
    @Column(name="lfs_nome_jogo", nullable=false, length=50)
    public String getLfsNomeJogo() {
        return this.lfsNomeJogo;
    }
    
    public void setLfsNomeJogo(String lfsNomeJogo) {
        this.lfsNomeJogo = lfsNomeJogo;
    }

    
    @Column(name="lfs_classificacao_indicativa", nullable=false, length=2)
    public String getLfsClassificacaoIndicativa() {
        return this.lfsClassificacaoIndicativa;
    }
    
    public void setLfsClassificacaoIndicativa(String lfsClassificacaoIndicativa) {
        this.lfsClassificacaoIndicativa = lfsClassificacaoIndicativa;
    }

    
    @Column(name="lfs_genero", nullable=false, length=50)
    public String getLfsGenero() {
        return this.lfsGenero;
    }
    
    public void setLfsGenero(String lfsGenero) {
        this.lfsGenero = lfsGenero;
    }

    
    @Column(name="lfs_preco", nullable=false, precision=10)
    public double getLfsPreco() {
        return this.lfsPreco;
    }
    
    public void setLfsPreco(double lfsPreco) {
        this.lfsPreco = lfsPreco;
    }

    
    @Column(name="lfs_descricao", nullable=false)
    public String getLfsDescricao() {
        return this.lfsDescricao;
    }
    
    public void setLfsDescricao(String lfsDescricao) {
        this.lfsDescricao = lfsDescricao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lfs_data_lancamento", length=10)
    public Date getLfsDataLancamento() {
        return this.lfsDataLancamento;
    }
    
    public void setLfsDataLancamento(Date lfsDataLancamento) {
        this.lfsDataLancamento = lfsDataLancamento;
    }

    
    @Column(name="lfs_estoque", nullable=false, length=6)
    public String getLfsEstoque() {
        return this.lfsEstoque;
    }
    
    public void setLfsEstoque(String lfsEstoque) {
        this.lfsEstoque = lfsEstoque;
    }

    
    @Column(name="lfs_idioma", nullable=false, length=30)
    public String getLfsIdioma() {
        return this.lfsIdioma;
    }
    
    public void setLfsIdioma(String lfsIdioma) {
        this.lfsIdioma = lfsIdioma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lfs_data_adicionado", length=10)
    public Date getLfsDataAdicionado() {
        return this.lfsDataAdicionado;
    }
    
    public void setLfsDataAdicionado(Date lfsDataAdicionado) {
        this.lfsDataAdicionado = lfsDataAdicionado;
    }

    
    @Column(name="lfs_desenvolvedora", nullable=false, length=60)
    public String getLfsDesenvolvedora() {
        return this.lfsDesenvolvedora;
    }
    
    public void setLfsDesenvolvedora(String lfsDesenvolvedora) {
        this.lfsDesenvolvedora = lfsDesenvolvedora;
    }

    
    @Column(name="lfs_avaliacao_media", nullable=false, length=2)
    public String getLfsAvaliacaoMedia() {
        return this.lfsAvaliacaoMedia;
    }
    
    public void setLfsAvaliacaoMedia(String lfsAvaliacaoMedia) {
        this.lfsAvaliacaoMedia = lfsAvaliacaoMedia;
    }

    
    @Column(name="lfs_modo_de_jogo", nullable=false, length=30)
    public String getLfsModoDeJogo() {
        return this.lfsModoDeJogo;
    }
    
    public void setLfsModoDeJogo(String lfsModoDeJogo) {
        this.lfsModoDeJogo = lfsModoDeJogo;
    }

    
    @Column(name="lfs_plataforma", nullable=false, length=54)
    public String getLfsPlataforma() {
        return this.lfsPlataforma;
    }
    
    public void setLfsPlataforma(String lfsPlataforma) {
        this.lfsPlataforma = lfsPlataforma;
    }

    
    @Column(name="lfs_status_disponibilidade", nullable=false, length=20)
    public String getLfsStatusDisponibilidade() {
        return this.lfsStatusDisponibilidade;
    }
    
    public void setLfsStatusDisponibilidade(String lfsStatusDisponibilidade) {
        this.lfsStatusDisponibilidade = lfsStatusDisponibilidade;
    }





}


