package bean;
// Generated 15/10/2025 12:59:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LfsUsuario generated by hbm2java
 */
@Entity
@Table(name="lfs_usuario"
    ,catalog="db_laura_silva"
)
public class LfsUsuario  implements java.io.Serializable {


     private int lfsIdusuario;
     private String lfsNome;
     private String lfsApelido;
     private String lfsCpf;
     private Date lfsDataNascimento;
     private String lfsSenha;
     private int lfsNivel;
     private String lfsAtivo;

    public LfsUsuario() {
    }

	
    public LfsUsuario(int lfsIdusuario, String lfsNome, String lfsApelido, String lfsCpf, String lfsSenha, int lfsNivel, String lfsAtivo) {
        this.lfsIdusuario = lfsIdusuario;
        this.lfsNome = lfsNome;
        this.lfsApelido = lfsApelido;
        this.lfsCpf = lfsCpf;
        this.lfsSenha = lfsSenha;
        this.lfsNivel = lfsNivel;
        this.lfsAtivo = lfsAtivo;
    }
    public LfsUsuario(int lfsIdusuario, String lfsNome, String lfsApelido, String lfsCpf, Date lfsDataNascimento, String lfsSenha, int lfsNivel, String lfsAtivo) {
       this.lfsIdusuario = lfsIdusuario;
       this.lfsNome = lfsNome;
       this.lfsApelido = lfsApelido;
       this.lfsCpf = lfsCpf;
       this.lfsDataNascimento = lfsDataNascimento;
       this.lfsSenha = lfsSenha;
       this.lfsNivel = lfsNivel;
       this.lfsAtivo = lfsAtivo;
    }
   
     @Id 

    
    @Column(name="lfs_idusuario", unique=true, nullable=false)
    public int getLfsIdusuario() {
        return this.lfsIdusuario;
    }
    
    public void setLfsIdusuario(int lfsIdusuario) {
        this.lfsIdusuario = lfsIdusuario;
    }

    
    @Column(name="lfs_nome", nullable=false, length=45)
    public String getLfsNome() {
        return this.lfsNome;
    }
    
    public void setLfsNome(String lfsNome) {
        this.lfsNome = lfsNome;
    }

    
    @Column(name="lfs_apelido", nullable=false, length=30)
    public String getLfsApelido() {
        return this.lfsApelido;
    }
    
    public void setLfsApelido(String lfsApelido) {
        this.lfsApelido = lfsApelido;
    }

    
    @Column(name="lfs_cpf", nullable=false, length=14)
    public String getLfsCpf() {
        return this.lfsCpf;
    }
    
    public void setLfsCpf(String lfsCpf) {
        this.lfsCpf = lfsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lfs_dataNascimento", length=10)
    public Date getLfsDataNascimento() {
        return this.lfsDataNascimento;
    }
    
    public void setLfsDataNascimento(Date lfsDataNascimento) {
        this.lfsDataNascimento = lfsDataNascimento;
    }

    
    @Column(name="lfs_senha", nullable=false, length=20)
    public String getLfsSenha() {
        return this.lfsSenha;
    }
    
    public void setLfsSenha(String lfsSenha) {
        this.lfsSenha = lfsSenha;
    }

    
    @Column(name="lfs_nivel", nullable=false)
    public int getLfsNivel() {
        return this.lfsNivel;
    }
    
    public void setLfsNivel(int lfsNivel) {
        this.lfsNivel = lfsNivel;
    }

    
    @Column(name="lfs_ativo", nullable=false, length=1)
    public String getLfsAtivo() {
        return this.lfsAtivo;
    }
    
    public void setLfsAtivo(String lfsAtivo) {
        this.lfsAtivo = lfsAtivo;
    }




}


