package bean;
// Generated 15/10/2025 12:59:38 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LfsVendasJogosId generated by hbm2java
 */
@Embeddable
public class LfsVendasJogosId  implements java.io.Serializable {


     private int lfsIdVendaJogos;
     private int lfsFkJogos;
     private int lfsFksIdVenda;

    public LfsVendasJogosId() {
    }

    public LfsVendasJogosId(int lfsIdVendaJogos, int lfsFkJogos, int lfsFksIdVenda) {
       this.lfsIdVendaJogos = lfsIdVendaJogos;
       this.lfsFkJogos = lfsFkJogos;
       this.lfsFksIdVenda = lfsFksIdVenda;
    }
   


    @Column(name="lfs_idVenda_jogos", nullable=false)
    public int getLfsIdVendaJogos() {
        return this.lfsIdVendaJogos;
    }
    
    public void setLfsIdVendaJogos(int lfsIdVendaJogos) {
        this.lfsIdVendaJogos = lfsIdVendaJogos;
    }


    @Column(name="lfs_fk_jogos", nullable=false)
    public int getLfsFkJogos() {
        return this.lfsFkJogos;
    }
    
    public void setLfsFkJogos(int lfsFkJogos) {
        this.lfsFkJogos = lfsFkJogos;
    }


    @Column(name="lfs_fks_idVenda", nullable=false)
    public int getLfsFksIdVenda() {
        return this.lfsFksIdVenda;
    }
    
    public void setLfsFksIdVenda(int lfsFksIdVenda) {
        this.lfsFksIdVenda = lfsFksIdVenda;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LfsVendasJogosId) ) return false;
		 LfsVendasJogosId castOther = ( LfsVendasJogosId ) other; 
         
		 return (this.getLfsIdVendaJogos()==castOther.getLfsIdVendaJogos())
 && (this.getLfsFkJogos()==castOther.getLfsFkJogos())
 && (this.getLfsFksIdVenda()==castOther.getLfsFksIdVenda());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLfsIdVendaJogos();
         result = 37 * result + this.getLfsFkJogos();
         result = 37 * result + this.getLfsFksIdVenda();
         return result;
   }   


}


