package bean;
// Generated 15/10/2025 12:59:38 by Hibernate Tools 4.3.1



import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LfsVendasJogos generated by hbm2java
 */
@Entity
@Table(name="lfs_vendas_jogos"
    ,catalog="db_laura_silva"
)
public class LfsVendasJogos  implements java.io.Serializable {


     private LfsVendasJogosId id;
     private LfsJogos lfsJogos;
     private LfsVenda lfsVenda;
     private int lfsQuantidade;
     private double lfsValorUnitario;
     private String lfsObservacoes;

    public LfsVendasJogos() {
    }

	
    public LfsVendasJogos(LfsVendasJogosId id, LfsJogos lfsJogos, LfsVenda lfsVenda, int lfsQuantidade, double lfsValorUnitario) {
        this.id = id;
        this.lfsJogos = lfsJogos;
        this.lfsVenda = lfsVenda;
        this.lfsQuantidade = lfsQuantidade;
        this.lfsValorUnitario = lfsValorUnitario;
    }
    public LfsVendasJogos(LfsVendasJogosId id, LfsJogos lfsJogos, LfsVenda lfsVenda, int lfsQuantidade, double lfsValorUnitario, String lfsObservacoes) {
       this.id = id;
       this.lfsJogos = lfsJogos;
       this.lfsVenda = lfsVenda;
       this.lfsQuantidade = lfsQuantidade;
       this.lfsValorUnitario = lfsValorUnitario;
       this.lfsObservacoes = lfsObservacoes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="lfsIdVendaJogos", column=@Column(name="lfs_idVenda_jogos", nullable=false) ), 
        @AttributeOverride(name="lfsFkJogos", column=@Column(name="lfs_fk_jogos", nullable=false) ), 
        @AttributeOverride(name="lfsFksIdVenda", column=@Column(name="lfs_fks_idVenda", nullable=false) ) } )
    public LfsVendasJogosId getId() {
        return this.id;
    }
    
    public void setId(LfsVendasJogosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lfs_fk_jogos", nullable=false, insertable=false, updatable=false)
    public LfsJogos getLfsJogos() {
        return this.lfsJogos;
    }
    
    public void setLfsJogos(LfsJogos lfsJogos) {
        this.lfsJogos = lfsJogos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lfs_fks_idVenda", nullable=false, insertable=false, updatable=false)
    public LfsVenda getLfsVenda() {
        return this.lfsVenda;
    }
    
    public void setLfsVenda(LfsVenda lfsVenda) {
        this.lfsVenda = lfsVenda;
    }

    
    @Column(name="lfs_quantidade", nullable=false)
    public int getLfsQuantidade() {
        return this.lfsQuantidade;
    }
    
    public void setLfsQuantidade(int lfsQuantidade) {
        this.lfsQuantidade = lfsQuantidade;
    }

    
    @Column(name="lfs_valor_unitario", nullable=false, precision=10)
    public double getLfsValorUnitario() {
        return this.lfsValorUnitario;
    }
    
    public void setLfsValorUnitario(double lfsValorUnitario) {
        this.lfsValorUnitario = lfsValorUnitario;
    }

    
    @Column(name="lfs_observacoes", length=256)
    public String getLfsObservacoes() {
        return this.lfsObservacoes;
    }
    
    public void setLfsObservacoes(String lfsObservacoes) {
        this.lfsObservacoes = lfsObservacoes;
    }




}


