package bean;
// Generated 15/10/2025 12:59:38 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LfsVenda generated by hbm2java
 */
@Entity
@Table(name="lfs_venda"
    ,catalog="db_laura_silva"
)
public class LfsVenda  implements java.io.Serializable {


     private int lfsIdVenda;
     private LfsCliente lfsCliente;
     private LfsVendedor lfsVendedor;
     private Date lfsDataVenda;
     private double lfsTotal;
     private String lfsStatusVenda;
     private String lfsObservacoes;

    public LfsVenda() {
    }

	
    public LfsVenda(int lfsIdVenda, double lfsTotal, String lfsStatusVenda, String lfsObservacoes) {
        this.lfsIdVenda = lfsIdVenda;
        this.lfsTotal = lfsTotal;
        this.lfsStatusVenda = lfsStatusVenda;
        this.lfsObservacoes = lfsObservacoes;
    }
    public LfsVenda(int lfsIdVenda, LfsCliente lfsCliente, LfsVendedor lfsVendedor, Date lfsDataVenda, double lfsTotal, String lfsStatusVenda, String lfsObservacoes) {
       this.lfsIdVenda = lfsIdVenda;
       this.lfsCliente = lfsCliente;
       this.lfsVendedor = lfsVendedor;
       this.lfsDataVenda = lfsDataVenda;
       this.lfsTotal = lfsTotal;
       this.lfsStatusVenda = lfsStatusVenda;
       this.lfsObservacoes = lfsObservacoes;
    }
   
     @Id 

    
    @Column(name="lfs_idVenda", unique=true, nullable=false)
    public int getLfsIdVenda() {
        return this.lfsIdVenda;
    }
    
    public void setLfsIdVenda(int lfsIdVenda) {
        this.lfsIdVenda = lfsIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lfs_fk_cliente")
    public LfsCliente getLfsCliente() {
        return this.lfsCliente;
    }
    
    public void setLfsCliente(LfsCliente lfsCliente) {
        this.lfsCliente = lfsCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lfs_fk_vendedor")
    public LfsVendedor getLfsVendedor() {
        return this.lfsVendedor;
    }
    
    public void setLfsVendedor(LfsVendedor lfsVendedor) {
        this.lfsVendedor = lfsVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lfs_dataVenda", length=10)
    public Date getLfsDataVenda() {
        return this.lfsDataVenda;
    }
    
    public void setLfsDataVenda(Date lfsDataVenda) {
        this.lfsDataVenda = lfsDataVenda;
    }

    
    @Column(name="lfs_total", nullable=false, precision=10)
    public double getLfsTotal() {
        return this.lfsTotal;
    }
    
    public void setLfsTotal(double lfsTotal) {
        this.lfsTotal = lfsTotal;
    }

    
    @Column(name="lfs_status_Venda", nullable=false, length=20)
    public String getLfsStatusVenda() {
        return this.lfsStatusVenda;
    }
    
    public void setLfsStatusVenda(String lfsStatusVenda) {
        this.lfsStatusVenda = lfsStatusVenda;
    }

    
    @Column(name="lfs_observacoes", nullable=false)
    public String getLfsObservacoes() {
        return this.lfsObservacoes;
    }
    
    public void setLfsObservacoes(String lfsObservacoes) {
        this.lfsObservacoes = lfsObservacoes;
    }

}


