package bean;
// Generated 15/10/2025 12:59:38 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LfsVendedor generated by hbm2java
 */
@Entity
@Table(name="lfs_vendedor"
    ,catalog="db_laura_silva"
)
public class LfsVendedor  implements java.io.Serializable {


     private int idlfsVendedor;
     private String lfsDescricao;
     private String lfsNome;
     private String lfsCpf;
     private Date lfsDataNascimento;
     private String lfsTelefone;
     private double lfsSalario;
     

    public LfsVendedor() {
    }

	
    public LfsVendedor(int idlfsVendedor, String lfsDescricao, String lfsNome, String lfsCpf, String lfsTelefone, double lfsSalario) {
        this.idlfsVendedor = idlfsVendedor;
        this.lfsDescricao = lfsDescricao;
        this.lfsNome = lfsNome;
        this.lfsCpf = lfsCpf;
        this.lfsTelefone = lfsTelefone;
        this.lfsSalario = lfsSalario;
    }
    public LfsVendedor(int idlfsVendedor, String lfsDescricao, String lfsNome, String lfsCpf, Date lfsDataNascimento, String lfsTelefone, double lfsSalario) {
       this.idlfsVendedor = idlfsVendedor;
       this.lfsDescricao = lfsDescricao;
       this.lfsNome = lfsNome;
       this.lfsCpf = lfsCpf;
       this.lfsDataNascimento = lfsDataNascimento;
       this.lfsTelefone = lfsTelefone;
       this.lfsSalario = lfsSalario;

    }
   
     @Id 

    
    @Column(name="idlfs_vendedor", unique=true, nullable=false)
    public int getIdlfsVendedor() {
        return this.idlfsVendedor;
    }
    
    public void setIdlfsVendedor(int idlfsVendedor) {
        this.idlfsVendedor = idlfsVendedor;
    }

    
    @Column(name="lfs_descricao", nullable=false)
    public String getLfsDescricao() {
        return this.lfsDescricao;
    }
    
    public void setLfsDescricao(String lfsDescricao) {
        this.lfsDescricao = lfsDescricao;
    }

    
    @Column(name="lfs_nome", nullable=false, length=30)
    public String getLfsNome() {
        return this.lfsNome;
    }
    
    public void setLfsNome(String lfsNome) {
        this.lfsNome = lfsNome;
    }

    
    @Column(name="lfs_cpf", nullable=false, length=14)
    public String getLfsCpf() {
        return this.lfsCpf;
    }
    
    public void setLfsCpf(String lfsCpf) {
        this.lfsCpf = lfsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lfs_data_nascimento", length=10)
    public Date getLfsDataNascimento() {
        return this.lfsDataNascimento;
    }
    
    public void setLfsDataNascimento(Date lfsDataNascimento) {
        this.lfsDataNascimento = lfsDataNascimento;
    }

    
    @Column(name="lfs_telefone", nullable=false, length=15)
    public String getLfsTelefone() {
        return this.lfsTelefone;
    }
    
    public void setLfsTelefone(String lfsTelefone) {
        this.lfsTelefone = lfsTelefone;
    }

    
    @Column(name="lfs_salario", nullable=false, precision=10)
    public double getLfsSalario() {
        return this.lfsSalario;
    }
    
    public void setLfsSalario(double lfsSalario) {
        this.lfsSalario = lfsSalario;
    }
    
    @Override
    public String toString() {
        return this.getLfsNome();
    }

 public boolean equals(Object object) {
        if (object instanceof LfsVendedor) {
            LfsVendedor lfsvendedor = (LfsVendedor) object;
            if (lfsvendedor.getIdlfsVendedor() == this.getIdlfsVendedor()) {
                return true;
            }
        }
        return false;
    }



}


